<?php
/**
 * Phases de projet (export production 30.09.2026)
 * Appliqué seulement si la table est vide (voir seed() de l'installateur).
 */
defined('ABSPATH') || exit;

return [
    ['Id' => 1, 'Ordre' => 6, 'SlugPhase' => 'CmdViag', 'type_prestation' => '', 'TitrePhase' => 'Save order', 'TitrePhaseFuture' => 'Save order', 'TitrePhaseProgression' => '', 'VisuClient' => 1, 'VisuProgression' => 0, 'display_on_qotation' => 0, 'Color' => 'var(--ispag-red)', 'ActionText' => null, 'is_automatic' => 0, 'waitNextStep' => 0, 'CloseProject' => 0, 'Brevo_id' => 76, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 2, 'Ordre' => 19, 'SlugPhase' => 'ConfCmdClient', 'type_prestation' => '', 'TitrePhase' => 'Order confirmation', 'TitrePhaseFuture' => 'Send order confirmation', 'TitrePhaseProgression' => 'Saved', 'VisuClient' => 1, 'VisuProgression' => 1, 'display_on_qotation' => 0, 'Color' => 'var(--ispag-blue)', 'ActionText' => null, 'is_automatic' => 0, 'waitNextStep' => 0, 'CloseProject' => 0, 'Brevo_id' => 0, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 3, 'Ordre' => 7, 'SlugPhase' => 'CmdFournisseur', 'type_prestation' => '', 'TitrePhase' => 'Supplier order', 'TitrePhaseFuture' => 'Send supplier order', 'TitrePhaseProgression' => '', 'VisuClient' => 0, 'VisuProgression' => 0, 'display_on_qotation' => 1, 'Color' => 'var(--ispag-orange)', 'ActionText' => null, 'is_automatic' => 1, 'waitNextStep' => 0, 'CloseProject' => 0, 'Brevo_id' => 0, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 4, 'Ordre' => 8, 'SlugPhase' => 'PlanFournisseur', 'type_prestation' => 'Product', 'TitrePhase' => 'Supplier drawing', 'TitrePhaseFuture' => 'Receive supplier drawing', 'TitrePhaseProgression' => 'Supplier drawing', 'VisuClient' => 0, 'VisuProgression' => 1, 'display_on_qotation' => 0, 'Color' => 'var(--ispag-blue)', 'ActionText' => null, 'is_automatic' => 1, 'waitNextStep' => 0, 'CloseProject' => 0, 'Brevo_id' => 0, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 5, 'Ordre' => 9, 'SlugPhase' => 'CheckLongueurPiquage', 'type_prestation' => 'Product', 'TitrePhase' => 'Fitting length', 'TitrePhaseFuture' => 'Check fittings length', 'TitrePhaseProgression' => '', 'VisuClient' => 0, 'VisuProgression' => 0, 'display_on_qotation' => 0, 'Color' => 'var(--ispag-orange)', 'ActionText' => null, 'is_automatic' => 0, 'waitNextStep' => 0, 'CloseProject' => 0, 'Brevo_id' => 0, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 6, 'Ordre' => 12, 'SlugPhase' => 'EnvoiePlanClient', 'type_prestation' => 'Product', 'TitrePhase' => 'Customer drawing', 'TitrePhaseFuture' => 'Send drawings to customer', 'TitrePhaseProgression' => 'Drawing sent', 'VisuClient' => 1, 'VisuProgression' => 1, 'display_on_qotation' => 0, 'Color' => 'var(--ispag-blue)', 'ActionText' => null, 'is_automatic' => 0, 'waitNextStep' => 1, 'CloseProject' => 0, 'Brevo_id' => 78, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 7, 'Ordre' => 14, 'SlugPhase' => 'SignaturePlan', 'type_prestation' => 'Product', 'TitrePhase' => 'Drawing approval', 'TitrePhaseFuture' => 'Wait customer drawings validation', 'TitrePhaseProgression' => 'Drawing approuved', 'VisuClient' => 1, 'VisuProgression' => 1, 'display_on_qotation' => 0, 'Color' => 'var(--ispag-blue)', 'ActionText' => null, 'is_automatic' => 1, 'waitNextStep' => 0, 'CloseProject' => 0, 'Brevo_id' => 64, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 8, 'Ordre' => 17, 'SlugPhase' => 'DateLivraisonCuve', 'type_prestation' => '', 'TitrePhase' => 'Delivery date', 'TitrePhaseFuture' => 'Send delivery date information', 'TitrePhaseProgression' => 'Manufacturing', 'VisuClient' => 1, 'VisuProgression' => 1, 'display_on_qotation' => 0, 'Color' => 'var(--ispag-blue)', 'ActionText' => null, 'is_automatic' => 0, 'waitNextStep' => 1, 'CloseProject' => 0, 'Brevo_id' => 79, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 9, 'Ordre' => 80, 'SlugPhase' => 'ProductDelivered', 'type_prestation' => 'Product', 'TitrePhase' => 'Tank delivery', 'TitrePhaseFuture' => 'Delivery tank', 'TitrePhaseProgression' => 'Tank delivered', 'VisuClient' => 1, 'VisuProgression' => 1, 'display_on_qotation' => 0, 'Color' => 'var(--ispag-green)', 'ActionText' => null, 'is_automatic' => 1, 'waitNextStep' => 0, 'CloseProject' => 0, 'Brevo_id' => 26, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 10, 'Ordre' => 90, 'SlugPhase' => 'ProductInvoice', 'type_prestation' => 'Product', 'TitrePhase' => 'Tank invoiced', 'TitrePhaseFuture' => 'Invoice tank', 'TitrePhaseProgression' => '', 'VisuClient' => 0, 'VisuProgression' => 0, 'display_on_qotation' => 0, 'Color' => 'var(--ispag-green)', 'ActionText' => null, 'is_automatic' => 1, 'waitNextStep' => 0, 'CloseProject' => 0, 'Brevo_id' => 0, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 11, 'Ordre' => 81, 'SlugPhase' => 'WeldingDelivered', 'type_prestation' => 'Welding', 'TitrePhase' => 'Welding', 'TitrePhaseFuture' => 'Welding', 'TitrePhaseProgression' => 'Welding', 'VisuClient' => 1, 'VisuProgression' => 1, 'display_on_qotation' => 0, 'Color' => 'var(--ispag-green)', 'ActionText' => null, 'is_automatic' => 1, 'waitNextStep' => 0, 'CloseProject' => 0, 'Brevo_id' => 0, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 12, 'Ordre' => 91, 'SlugPhase' => 'WeldingInvoice', 'type_prestation' => 'Welding', 'TitrePhase' => 'Welding invoiced', 'TitrePhaseFuture' => 'Invoice welding', 'TitrePhaseProgression' => '', 'VisuClient' => 0, 'VisuProgression' => 0, 'display_on_qotation' => 0, 'Color' => 'var(--ispag-green)', 'ActionText' => null, 'is_automatic' => 1, 'waitNextStep' => 0, 'CloseProject' => 0, 'Brevo_id' => 0, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 13, 'Ordre' => 82, 'SlugPhase' => 'IsolDelivered', 'type_prestation' => 'Isol', 'TitrePhase' => 'Insulation', 'TitrePhaseFuture' => 'Insulation', 'TitrePhaseProgression' => 'Insulation', 'VisuClient' => 1, 'VisuProgression' => 1, 'display_on_qotation' => 0, 'Color' => 'var(--ispag-green)', 'ActionText' => null, 'is_automatic' => 1, 'waitNextStep' => 0, 'CloseProject' => 0, 'Brevo_id' => 0, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 14, 'Ordre' => 92, 'SlugPhase' => 'IsolInvoice', 'type_prestation' => 'Isol', 'TitrePhase' => 'Insulation invoiced', 'TitrePhaseFuture' => 'Invoice insulation', 'TitrePhaseProgression' => '', 'VisuClient' => 0, 'VisuProgression' => 0, 'display_on_qotation' => 0, 'Color' => 'var(--ispag-green)', 'ActionText' => null, 'is_automatic' => 1, 'waitNextStep' => 0, 'CloseProject' => 0, 'Brevo_id' => 0, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 23, 'Ordre' => 16, 'SlugPhase' => 'checkOrderedQty', 'type_prestation' => '', 'TitrePhase' => 'Check ordered qty', 'TitrePhaseFuture' => 'Check ordered qty', 'TitrePhaseProgression' => 'Check ordered qty', 'VisuClient' => 0, 'VisuProgression' => 0, 'display_on_qotation' => 0, 'Color' => 'var(--ispag-orange)', 'ActionText' => null, 'is_automatic' => 0, 'waitNextStep' => 0, 'CloseProject' => 0, 'Brevo_id' => 0, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 24, 'Ordre' => 20, 'SlugPhase' => 'UnloadingFacility', 'type_prestation' => '', 'TitrePhase' => 'unloading facility', 'TitrePhaseFuture' => 'Check unloading facility', 'TitrePhaseProgression' => '', 'VisuClient' => 1, 'VisuProgression' => 1, 'display_on_qotation' => 0, 'Color' => 'var(--ispag-blue)', 'ActionText' => null, 'is_automatic' => 0, 'waitNextStep' => 0, 'CloseProject' => 0, 'Brevo_id' => 70, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 25, 'Ordre' => 10, 'SlugPhase' => 'CheckIfWelding', 'type_prestation' => 'Product', 'TitrePhase' => 'Check if welding', 'TitrePhaseFuture' => 'Check if welding', 'TitrePhaseProgression' => '', 'VisuClient' => 0, 'VisuProgression' => 0, 'display_on_qotation' => 0, 'Color' => 'var(--ispag-orange)', 'ActionText' => null, 'is_automatic' => 0, 'waitNextStep' => 0, 'CloseProject' => 0, 'Brevo_id' => 0, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 26, 'Ordre' => 11, 'SlugPhase' => 'CheckIsolWithTank', 'type_prestation' => 'Product', 'TitrePhase' => 'Check if isol with tank', 'TitrePhaseFuture' => 'Check if isol with tank', 'TitrePhaseProgression' => '', 'VisuClient' => 0, 'VisuProgression' => 0, 'display_on_qotation' => 0, 'Color' => 'var(--ispag-orange)', 'ActionText' => null, 'is_automatic' => 0, 'waitNextStep' => 0, 'CloseProject' => 0, 'Brevo_id' => 0, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 27, 'Ordre' => 83, 'SlugPhase' => 'divDelivered', 'type_prestation' => 'div', 'TitrePhase' => 'Accessories', 'TitrePhaseFuture' => 'Send accessories', 'TitrePhaseProgression' => 'Accessoiries', 'VisuClient' => 1, 'VisuProgression' => 1, 'display_on_qotation' => 0, 'Color' => 'var(--ispag-green)', 'ActionText' => null, 'is_automatic' => 1, 'waitNextStep' => 0, 'CloseProject' => 0, 'Brevo_id' => 0, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 28, 'Ordre' => 93, 'SlugPhase' => 'divInvoice', 'type_prestation' => 'div', 'TitrePhase' => 'Accessories invoice', 'TitrePhaseFuture' => 'Invoice accessories', 'TitrePhaseProgression' => 'Accessoiries invoice', 'VisuClient' => 0, 'VisuProgression' => 0, 'display_on_qotation' => 0, 'Color' => 'var(--ispag-green)', 'ActionText' => null, 'is_automatic' => 1, 'waitNextStep' => 0, 'CloseProject' => 0, 'Brevo_id' => 0, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 29, 'Ordre' => 100, 'SlugPhase' => 'SatisfactionSurvey', 'type_prestation' => '', 'TitrePhase' => 'Satisfaction survey', 'TitrePhaseFuture' => 'Send satisfaction survey', 'TitrePhaseProgression' => 'Satisfaction survey', 'VisuClient' => 0, 'VisuProgression' => 0, 'display_on_qotation' => 0, 'Color' => 'var(--ispag-grey)', 'ActionText' => null, 'is_automatic' => 0, 'waitNextStep' => 0, 'CloseProject' => 0, 'Brevo_id' => 91, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 30, 'Ordre' => 101, 'SlugPhase' => 'PictureProject', 'type_prestation' => '', 'TitrePhase' => 'Pictures', 'TitrePhaseFuture' => 'Photos du projet', 'TitrePhaseProgression' => 'Photos du projet', 'VisuClient' => 0, 'VisuProgression' => 1, 'display_on_qotation' => 0, 'Color' => 'var(--ispag-grey)', 'ActionText' => null, 'is_automatic' => 0, 'waitNextStep' => 0, 'CloseProject' => 0, 'Brevo_id' => 0, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 31, 'Ordre' => 102, 'SlugPhase' => 'post_linkedin', 'type_prestation' => '', 'TitrePhase' => 'Post linkedin', 'TitrePhaseFuture' => '', 'TitrePhaseProgression' => '', 'VisuClient' => 0, 'VisuProgression' => 0, 'display_on_qotation' => 0, 'Color' => 'var(--ispag-grey)', 'ActionText' => null, 'is_automatic' => 0, 'waitNextStep' => 0, 'CloseProject' => 1, 'Brevo_id' => 0, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 32, 'Ordre' => 15, 'SlugPhase' => 'id_plate', 'type_prestation' => 'Product', 'TitrePhase' => 'Order Id plate', 'TitrePhaseFuture' => '', 'TitrePhaseProgression' => '', 'VisuClient' => 0, 'VisuProgression' => 0, 'display_on_qotation' => 0, 'Color' => 'var(--ispag-blue)', 'ActionText' => null, 'is_automatic' => 0, 'waitNextStep' => 0, 'CloseProject' => 0, 'Brevo_id' => 0, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 33, 'Ordre' => 5, 'SlugPhase' => 'get_customer_order', 'type_prestation' => '', 'TitrePhase' => 'Get customer order', 'TitrePhaseFuture' => '', 'TitrePhaseProgression' => '', 'VisuClient' => 0, 'VisuProgression' => 0, 'display_on_qotation' => 0, 'Color' => 'var(--ispag-red)', 'ActionText' => null, 'is_automatic' => 1, 'waitNextStep' => 0, 'CloseProject' => 0, 'Brevo_id' => 0, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 34, 'Ordre' => 3, 'SlugPhase' => 'no_article', 'type_prestation' => '', 'TitrePhase' => 'No article(s)', 'TitrePhaseFuture' => '', 'TitrePhaseProgression' => '', 'VisuClient' => 0, 'VisuProgression' => 0, 'display_on_qotation' => 1, 'Color' => 'var(--ispag-red)', 'ActionText' => null, 'is_automatic' => 1, 'waitNextStep' => 0, 'CloseProject' => 0, 'Brevo_id' => 0, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 35, 'Ordre' => 1, 'SlugPhase' => 'customer_request', 'type_prestation' => '', 'TitrePhase' => 'Customer request', 'TitrePhaseFuture' => '', 'TitrePhaseProgression' => '', 'VisuClient' => 0, 'VisuProgression' => 0, 'display_on_qotation' => 1, 'Color' => 'var(--ispag-blue)', 'ActionText' => null, 'is_automatic' => 1, 'waitNextStep' => 0, 'CloseProject' => 0, 'Brevo_id' => 0, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 36, 'Ordre' => 4, 'SlugPhase' => 'all_items_have_sales_price', 'type_prestation' => '', 'TitrePhase' => 'Items need sales price', 'TitrePhaseFuture' => '', 'TitrePhaseProgression' => '', 'VisuClient' => 0, 'VisuProgression' => 0, 'display_on_qotation' => 1, 'Color' => 'var(--ispag-orange)', 'ActionText' => null, 'is_automatic' => 1, 'waitNextStep' => 0, 'CloseProject' => 0, 'Brevo_id' => 0, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 37, 'Ordre' => 18, 'SlugPhase' => 'webtool_drawing_update', 'type_prestation' => 'Product', 'TitrePhase' => 'Webtool drawing update', 'TitrePhaseFuture' => '', 'TitrePhaseProgression' => '', 'VisuClient' => 0, 'VisuProgression' => 0, 'display_on_qotation' => 0, 'Color' => 'var(--ispag-blue)', 'ActionText' => null, 'is_automatic' => 0, 'waitNextStep' => 0, 'CloseProject' => 0, 'Brevo_id' => 0, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 39, 'Ordre' => 2, 'SlugPhase' => 'competitor_in_request', 'type_prestation' => '', 'TitrePhase' => 'Competitor in request', 'TitrePhaseFuture' => '', 'TitrePhaseProgression' => '', 'VisuClient' => 0, 'VisuProgression' => 0, 'display_on_qotation' => 1, 'Color' => 'var(--ispag-orange)', 'ActionText' => null, 'is_automatic' => 1, 'waitNextStep' => 0, 'CloseProject' => 0, 'Brevo_id' => 0, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 41, 'Ordre' => 13, 'SlugPhase' => 'reviveProjectSign', 'type_prestation' => 'Product', 'TitrePhase' => 'Relance signature plan', 'TitrePhaseFuture' => 'Relance signature plan', 'TitrePhaseProgression' => 'Relance signature plan', 'VisuClient' => 0, 'VisuProgression' => 0, 'display_on_qotation' => 0, 'Color' => 'var(--ispag-orange)', 'ActionText' => null, 'is_automatic' => 1, 'waitNextStep' => 0, 'CloseProject' => 0, 'Brevo_id' => 18, 'Brevo_delay_days' => 0, 'JsHook' => null],
    ['Id' => 42, 'Ordre' => 21, 'SlugPhase' => 'welding_checklist', 'type_prestation' => 'Welding', 'TitrePhase' => 'Completed weld checklist', 'TitrePhaseFuture' => '', 'TitrePhaseProgression' => '', 'VisuClient' => 0, 'VisuProgression' => 1, 'display_on_qotation' => 0, 'Color' => '', 'ActionText' => null, 'is_automatic' => 0, 'waitNextStep' => 0, 'CloseProject' => 0, 'Brevo_id' => 0, 'Brevo_delay_days' => 0, 'JsHook' => null],
];
